### ISSUE TITLE
弹幕还是解析不出来...

### ISSUE THREAD

**Issue by daofeng2015** [kdxcxs/BilibiliLiveLottery#1]
运行了项目.看了下控制台.显示json解析错误...

**Comment by kdxcxs** [comment]
不好意思,现在才看到(刚高考完).
这个部分我是参考的 [Bilibili-Live-API](https://github.com/lovelyyoshino/Bilibili-Live-API/blob/master/API.WebSocket.md) 这个项目的,可能B站改协议了.后续找到新的协议之后会更新的,欢迎提PR.

**Comment by daofeng2015** [comment]
> 不好意思,现在才看到(刚高考完).
> 这个部分我是参考的 [Bilibili-Live-API](https://github.com/lovelyyoshino/Bilibili-Live-API/blob/master/API.WebSocket.md) 这个项目的,可能B站改协议了.后续找到新的协议之后会更新的,欢迎提PR.

我尝试更换了协议,已经成功了,用的[点击](https://github.com/simon300000/bilibili-live-ws)这个项目
